### ISSUE TITLE
The deployment gives quite a few errors, what would be the recommended python version for all the modules to work ? 

### ISSUE THREAD

**Issue by razvaniacob8778** [CiscoDevNet/netACL#4]
For example, this is the latest error I'm trying to fix:

[root@GRAFANA-NET netACL-master]# python -m frontend.rest_server_v5
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/root/netACL-master/frontend/rest_server_v5.py", line 17, in <module>
    import ConfigParser
ModuleNotFoundError: No module named 'ConfigParser'

Where:

[root@GRAFANA-NET netACL-master]# pip list | grep configparser
configparser 5.0.2

[root@GRAFANA-NET netACL-master]# python -V
Python 3.8.3

Can you please give me a clue what I'm doing wrong?

Thanks,
Razvan.

**Comment by nikmon2** [comment]
This was written for python 2.7. 
cheers,
Nik

**Comment by razvaniacob8778** [comment]
> This was written for python 2.7.
> cheers,
> Nik

**Comment by razvaniacob8778** [comment]
Hey Nik,
Yup, managed to run the front and backend with 2.7 indeed, but couldn't make it work with 3.8. Many thanks for the quick reply. Will start deploying  ODL tomorrow and see how everything fits togther, been looking for an easier way to manage ACLs for some time now. 

Thanks again,
Razvan
